name: myfirstyamlfile

on:
  workflow_dispatch: 
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: ubuntu latest job1
        run: echo "hello this is first step of job1"
  job2:
    runs-on: macos-latest
    steps:
      - name: macos latest job2
        run: echo "This is macos latest running job2"
  job3:
    runs-on: windows-latest
    steps:
      - name: windows latest job3 
        run: echo "This is windowsos running job3" 
  
