name: Azure login demo test

on:
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az group list -o table
            
      - name: TERRAFORM SETUP  
        uses: hashicorp/setup-terraform@v4
        
      - name: CHECKOUT REPO
        uses: actions/checkout@v7
        
      - name: TERRAFORM INIT  
        run: terraform init
        
      - name: TERRAFORM VALIDATE 
        run: terraform validate
        
      - name: TERRAFORM PLAN 
        run: terraform plan
        
      - name: TERRAFORM APPLY   
        run: terraform apply -auto-approve
    
     

  job1:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: ubuntu latest job1
        run: echo "hello this is first step of job1"

              
  job2:
    needs: job1
    runs-on: macos-latest
    steps:
      - name: macos latest job2
        run: echo "This is macos latest running job2"
  job3:
    needs:
      - build-and-deploy 
      - job1
      - job2
    runs-on: windows-latest
    steps:
      - name: windows latest job3 
        run: echo "This is windowsos running job3" 
  
